# Change prefix to Backtick
unbind C-b
set -g prefix `
bind ` send-prefix

# My plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @mighty-scroll-pass-through 'lnav less vim'
set -g @plugin "aless3/tmux-click-copy"

# My Theme
set -g @plugin 'dracula/tmux'
if-shell 'uname | grep -q Linux' \
  'set -g @dracula-plugins "cpu-usage ram-usage network-bandwidth ssh-session"' \
  'set -g @dracula-plugins "cpu-usage ram-usage network-bandwidth"'
set -g @dracula-ram-usage-colors "pink dark_gray"
set -g @dracula-show-location false
set -g @continuum-restore 'on'

# Intuitive pane splitting
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Scroll speed
setw -g mouse on
bind -T copy-mode WheelUpPane send -N1 -X scroll-up
bind -T copy-mode WheelDownPane send -N1 -X scroll-down

# Vim mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line

# Move between panes Vim style
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind L last-window

# Kill pane without confirmation
bind-key x kill-pane

# Jump to previous/next prompt
bind-key -T copy-mode-vi p send-keys -X search-backward "❯ "
bind-key -T copy-mode-vi P send-keys -X search-forward "❯ "

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
